# Generated by Django 5.2.12 on 2026-03-26 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_itemview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_clicks', to='wishlist.wishlistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
