# Generated by Django 5.2.12 on 2026-03-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_storeclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
