# Generated by Django 5.2.12 on 2026-03-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_rename_user_event_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist'),
        ),
    ]
