# Generated by Django 5.2.12 on 2026-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
